[package]
name = "rlp_compress"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
rlp = { git = "https://github.com/CodeChain-io/rlp.git", version = "0.4" }
lazy_static = "1.0"
